name: Prettier Format

on:
  push:
    branches-ignore: master
    paths:
      - 'ui/**'
      - '.github/workflows/prettier-format.yml'

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: prettier
        uses: creyD/prettier_action@v3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prettier_options: '--write ui/**/*.{json,css,js,ts,tsx}'
          commit_message: "format: prettier"
